url: "http://localhost:8080/demo/index.html"
steps:
  - action: click
    selector: "#start"
  - action: wait_for_voice
  - action: wait_for_silence
  - action: speak
    # text: "Hello, this is a test." 
    file: hello_make_an_appointment.mp3
  # - action: listen
  #   evaluate: "It is greeting the user"
  - action: wait_for_voice
    metrics: elapsed_time
  - action: wait_for_silence
  - action: speak
    file: name_lebron_james.mp3
  - action: wait_for_voice
    metrics: elapsed_time